
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('podcasts').del()
    .then(function () {
      // Inserts seed entries
      return knex('podcasts').insert([
          {id: 1, 
          title: 'Very Bad Wizards',
          image_URL: 'https://images.fireside.fm/podcasts/images/1/14eb939b-3c20-478e-b284-c7e3e642f7b3/cover.jpg',
          description: 'Very Bad Wizards is a podcast featuring a philosopher (Tamler Sommers) and a psychologist (David Pizarro), who share a love for ethics, pop culture, and cognitive science, and who have a marked inability to distinguish sacred from profane. Each podcast includes discussions of moral philosophy, recent work on moral psychology and neuroscience, and the overlap between the two.',
          rss_feed: 'https://verybadwizards.fireside.fm/rss',
          latest_pub_date: 'Tue, 23 Jan 2018 18:00:00 -0500',
          website: 'https://verybadwizards.fireside.fm/'},
          {id: 2, 
          title: 'Stuff You Should Know',
          image_URL: 'https://podcasts.howstuffworks.com/hsw/podcasts/sysk/sysk-audio-1600.jpg',
          description: 'How do landfills work? How do mosquitos work? Join Josh and Chuck as they explore the Stuff You Should Know about everything from genes to the Galapagos in this podcast from HowStuffWorks.com.',
          rss_feed: 'https://www.howstuffworks.com/podcasts/stuff-you-should-know.rss',
          latest_pub_date: 'Sat, 27 Jan 2018 06:30:03 -0500',
          website: 'https://www.howstuffworks.com/'},
          {id: 3,
          title: '99% Invisible',
          image_URL: 'http://is4.mzstatic.com/image/thumb/Music19/v4/30/49/06/3049067c-b15a-6549-45f5-45b192155ee4/source/1200x630bb.jpg',
          rss_feed: ' http://feeds.99percentinvisible.org/99percentinvisible',
          description: '99% Invisible is an independently produced radio show created by Roman Mars that focuses on design and architecture. '},
          {id: 4,
          title: 'The Daily',
          image_URL: 'https://dfkfj8j276wwv.cloudfront.net/images/01/1b/f3/d6/011bf3d6-a448-4533-967b-e2f19e376480/7fdd4469c1b5cb3b66aa7dcc9fa21f138efe9a0310a8a269f3dcd07c83a552844fcc445ea2d53db1e55d6fb077aeaa8a1566851f8f2d8ac4349d9d23a87a69f5.jpeg',
          description: 'This moment demands an explanation. This show is on a mission to find it. Only what you want to know, none of what you don’t. Hosted by Michael Barbaro. Powered by New York Times journalism. Twenty minutes a day, five days a week, ready by 6 a.m.',
          rss_feed: 'http://rss.art19.com/the-daily',
          latest_pub_date: 'Wed, 24 Jan 2018 11:03:36 -0000',
          website: 'https://art19.com/shows/the-daily'},
          {id: 5, 
          title: 'Vox\'s The Weeds',
          image_URL: 'https://cdn.vox-cdn.com/uploads/chorus_image/image/54055979/The_Weeds_podcast_Vox.0.png',
          description: 'Everyone is always warning you not to get lost in the weeds. But not Vox\'s Ezra Klein, Sarah Kliff, and Matthew Yglesias. They love the weeds. That\'s where all the policy is. This is the podcast for people who follow politics because they love thinking about health care, economics, and zoning. It is not a podcast for people who like hearing talk about gaffes.',
          rss_feed: 'http://feeds.feedburner.com/voxtheweeds',
          latest_pub_date: 'Tue, 16 Jan 2018 22:23:34 -0000',
          website: 'https://www.vox.com/the-weeds'},
          {id: 6,
          title: 'Slate Audio Book Club',
          image_URL: 'http://static.megaphone.fm/podcasts/30836968-8289-11e5-b42a-8b58d75e4327/image/uploads_2F1516106489105-h4f6038a6p-fa3e6d340872c743db8217528232fb09_2F01_Slate_Redux_Podcast_Cover_Audio-Book-Club.jpg',
          rss_feed: 'http://feeds.feedburner.com/SlateAudioBookClub',
          description: 'Join Slate\'s critics for monthly discussions of new and important books. Read the book club selections and then listen in as our critics hold lively - and sometimes heated - debates about the works. Part of the Panoply Network.'},
          { id: 7,
          title: 'S-Town',
          image_URL: 'https://upload.wikimedia.org/wikipedia/en/b/bd/S-Town_cover_art.jpg',
          description: 'S-Town is an investigative journalism podcast hosted by Brian Reed and created by the producers of Serial and This American Life',
          rss_feed: 'http://feeds.stownpodcast.org/stownpodcast'},
          {id: 8, 
          title: 'Recode Decode, hosted by Kara Swisher',
          image_URL: 'http://is4.mzstatic.com/image/thumb/Music62/v4/8c/43/83/8c4383ee-a7cd-6fcb-49df-6245c46fdd10/source/1200x630bb.jpg',
          description: 'One of tech\'s most prominent journalists, Kara Swisher is known for her insightful reporting and straight-shooting style. Listen in as she hosts hard-hitting interviews about the week in tech with influential business leaders and outspoken personalities from media, politics and more.',
          rss_feed: 'http://feeds.feedburner.com/Recode-Decode?format=xml',
          latest_pub_date: 'Wed, 17 Jan 2018 05:01:00 -0000',
          website: 'https://www.recode.net/podcasts/'},
          {id: 9, 
          title: 'Talk Python to Me',
          image_URL: 'https://talkpython.fm/static/img/podcast-theme-img_1400_v3.png',
          description: 'Talk Python to Me is a weekly podcast hosted by Michael Kennedy. The show covers a wide array of Python topics as well as many related topics (e.g. MongoDB, AngularJS, DevOps).The format is a casual 45 minute conversation with industry experts..',
          rss_feed: 'https://talkpython.fm/episodes/rss',
          latest_pub_date: 'Fri, 19 Jan 2018 00:00:00 -0800',
          website: 'https://talkpython.fm'},
          {id: 10, 
          title: 'Pod Save America',
          image_URL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjNeKsaN6CZe2aubZLzyeKPANSwfqykbE8SifjkbI1l58bzM-2',
          description: 'Four former aides to President Obama — Jon Favreau, Dan Pfeiffer, Jon Lovett, and Tommy Vietor — are joined by journalists, politicians, comedians, and activists for a freewheeling conversation about politics, the press and the challenges posed by the Trump presidency.',
          rss_feed: 'http://feeds.feedburner.com/pod-save-america?format=xml',
          latest_pub_date: 'Jan 22, 2018',
          website: 'https://art19.com/shows/pod-save-america'},
          {id: 11, 
          title: 'The Partially Examined Life Philosophy Podcast',
          image_URL: 'http://static.libsyn.com/p/assets/4/8/4/c/484cbe56ea2bd154/PartiallyExaminedLifeLogo_3000x3000.jpeg',
          description: 'The Partially Examined Life is a philosophy podcast by some guys who were at one point set on doing philosophy for a living but then thought better of it. Each episode, we pick a short text and chat about it with some balance between insight and flippancy. You don\'t have to know any philosophy, or even to have read the text we\'re talking about to (mostly) follow and (hopefully) enjoy the discussion.',
          rss_feed: 'http://partiallyexaminedlife.libsyn.com/rss',
          latest_pub_date: 'Mon, 22 Jan 2018 01:51:50 +0000',
          website: 'http://partiallyexaminedlife.com/'},
          {id: 12,
          title: 'See Something Say Something',
          image_URL: 'https://pbs.twimg.com/media/CvtySsZUEAAXceZ.jpg',
          rss_feed: 'http://feeds.feedburner.com/SeeSomethingSaySomething',
          description: 'Every week, BuzzFeed’s Ahmed Ali Akbar gathers folks together to drink tea, tell stories, and talk about being Muslim in America.'},
          {id: 13,
          title: 'The Joe Rogan Experience',
          image_URL: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMWY1NmFiOGQtMDM5Zi00M2RjLTk1ZjYtMDA5MmU4ZDBmZDA0XkEyXkFqcGdeQXVyNDc1ODgwOA@@._V1_.jpg',
          rss_feed: 'http://joeroganexp.joerogan.libsynpro.com/rss',
          description: 'The podcast of comedian Joe Rogan.'},
          {id: 14, 
          title: 'Hanselminutes',
          image_URL: 'http://www.pwop.com/itunes_hanselminutes.jpg',
          description: 'Fresh Air for Developers is a weekly talk show that brings interesting people together to talk about the web, culture, education, technology and more. Hosted by Scott Hanselman, this show promises fresh ideas and great people.',
          rss_feed: 'http://feeds.podtrac.com/P-4IIgRqsKI_',
          latest_pub_date: 'Mon, 15 Feb 2016 00:00:00 EST',
          website: 'https://hanselminutes.com/'},
          {id: 15, 
          title: 'Software Engineering Daily',
          image_URL: 'http://is1.mzstatic.com/image/thumb/Music62/v4/6e/3a/7f/6e3a7f2d-b42a-fddd-8761-f2bc316d20b9/source/170x170bb.jpg',
          description: 'We create and organize technical content about software.',
          rss_feed: 'http://softwareengineeringdaily.com/feed/podcast/',
          latest_pub_date: 'Fri, 19 Jan 2018 10:00:46 +0000',
          website: 'https://softwareengineeringdaily.com/'},
          {id: 16, 
          title: 'The Tim Ferriss Show',
          image_URL: 'https://dfkfj8j276wwv.cloudfront.net/images/69/10/10/fb/691010fb-625e-4abe-993c-a57228b28dbe/91cb53ae0d5dbb379b9dffecf0a772593891d0d09bbe6d90ee746edbdb79e3ec75584f2ceb8260e9f675a90c05419b9b99842a76905b686f0f51c1a9d3e227ab.jpeg',
          description: 'Tim Ferriss is a self-experimenter and bestselling author, best known for The 4-Hour Workweek, which has been translated into 40+ languages.  Newsweek calls him "the world\'s best human guinea pig," and The New York Times calls him "a cross between Jack Welch and a Buddhist monk."  In this show, he deconstructs world-class performers from eclectic areas (investing, chess, pro sports, etc.), digging deep to find the tools, tactics, and tricks that listeners can use.',
          rss_feed: 'https://rss.art19.com/tim-ferriss-show',
          latest_pub_date: 'Thu, 18 Jan 2018 20:48:21 -0000',
          website: 'https://tim.blog/podcast/'},
          {id: 17, 
          title: 'Song Exploder',
          image_URL: 'https://f.prxu.org/song-exploder/images/21201be4-830d-49ca-ac82-310d64511f5d/songexploder-logo.png',
          description: "Song Exploder is a podcast where musicians take apart their songs, and piece by piece, tell the story of how they were made. Each episode is produced and edited by host and creator Hrishikesh Hirway in Los Angeles. Using the isolated, individual tracks from a recording, Hrishikesh asks artists to delve into the specific decisions that went into creating their work. Hrishikesh edits the interviews, removing his side of the conversation and condensing the story to be tightly focused on how the artists brought their songs to life. Guests include Björk, U2, Metallica, Solange, and over a hundred more.",
          rss_feed: 'http://feed.songexploder.net/songexploder?format=xml',
          latest_pub_date: ' Wed, 17 Jan 2018 18:00:00 -0000',
          website: 'http://songexploder.net/'},
         
      ])
    }).then(() => {
      return knex.raw(
        `SELECT setval('podcasts_id_seq', (SELECT MAX(id) FROM podcasts));`
      )
    })
}
